apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ingester-secrets
  namespace: ingester
stringData:
  GEOCUBE_SERVER: {{GEOCUBE_SERVER}}
  GEOCUBE_CLIENTAPIKEY: ''
  STORAGE_URI: {{STORAGE_URI}}
  PEPS_USERNAME: ''
  PEPS_PASSWORD: ''
  CREODIAS_USERNAME: ''
  CREODIAS_PASSWORD: ''
  MUNDI_SEEED_TOKEN: ''
  ONDA_USERNAME: ''
  ONDA_PASSWORD: ''
  COPERNICUS_USERNAME: ''
  COPERNICUS_PASSWORD: ''
  ASF_TOKEN: ''
  GCS_PROVIDER_BUCKETS: 'gs://gcp-public-data-sentinel-2/tiles/{LATITUDE_BAND}/{GRID_SQUARE}/{GRANULE_ID}/{MISSION_ID}_MSI{PRODUCT_LEVEL}_{DATE}T{TIME}_*_R{ORBIT}_{TILE}_{PRODUCT_DISC}.SAFE'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ingester-db
  namespace: ingester
data:
  connection_string: {{DB_CONNECTION}}