apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ingester-secrets
  namespace: ingester
stringData:
  GEOCUBE_SERVER: {{GEOCUBE_SERVER}}
  GEOCUBE_CLIENTAPIKEY: ''
  STORAGE_URI: {{STORAGE_URI}}
  PEPS_USERNAME: ''
  PEPS_PASSWORD: ''
  CREODIAS_USERNAME: ''
  CREODIAS_PASSWORD: ''
  MUNDI_SEEED_TOKEN: ''
  ONDA_USERNAME: ''
  ONDA_PASSWORD: ''
  SCIHUB_USERNAME: ''
  SCIHUB_PASSWORD: ''
  SOBLOO_APIKEY: ''
  ASF_TOKEN: ''
  GCS_PROVIDER_BUCKETS: 'Sentinel2:gs://gcp-public-data-sentinel-2/tiles/{LATITUDE_BAND}/{GRID_SQUARE}/{GRANULE_ID}/{SCENE}.SAFE'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ingester-db
  namespace: ingester
data:
  connection_string: {{DB_CONNECTION}}