apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingester-workflow
  namespace: ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingester-workflow
  template:
    metadata:
      labels:
        app: ingester-workflow
    spec:
      automountServiceAccountToken: true
      serviceAccount: ingester-workflow-sa
      serviceAccountName: ingester-workflow-sa
      containers:
        - name: workflow
          image: {{WORKFLOW_IMAGE}}
          env:
            - name: DB_CONNECTION
              value: [Enter value]
            - name: GEOCUBE_SERVER
              value: [Enter value]
              value: [Enter value]
            - name: SCIHUB_USERNAME
              value: [Enter value]
            - name: SCIHUB_PASSWORD
              value: [Enter value]
          args:
            - "--db-connection=$(DB_CONNECTION)"
            - "--pgq-connection=$(DB_CONNECTION)"
            - "--event-queue=ingester-events"
            - "--downloader-queue=ingester-downloader"
            - "--processor-queue=ingester-processor"
            - "--namespace=ingester"
            - "--downloader-rc=ingester-downloader"
            - "--processor-rc=ingester-processor"
            - "--max-downloader=20"
            - "--max-processor=800"
            - "--geocube-server=$(GEOCUBE_SERVER)"
            - "--geocube-apikey=$(GEOCUBE_CLIENTAPIKEY)"
            - "--scihub-username=$(SCIHUB_USERNAME)"
            - "--scihub-password=$(SCIHUB_PASSWORD)"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 30Mi
          terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: ingester-downloader
  name: ingester-downloader
  namespace: ingester
spec:
  replicas: 0
  selector:
    app: ingester-downloader
  template:
    metadata:
      labels:
        app: ingester-downloader
    spec:
      containers:
        - name: ingester-downloader
          env:
            - name: DB_CONNECTION
              value: [Enter value]
            - name: STORAGE_URI
              value: [Enter value]
            - name: PEPS_USERNAME
              value: [Enter value]
            - name: PEPS_PASSWORD
              value: [Enter value]
            - name: ONDA_USERNAME
              value: [Enter value]
            - name: ONDA_PASSWORD
              value: [Enter value]
            - name: CREODIAS_USERNAME
              value: [Enter value]
            - name: CREODIAS_PASSWORD
              value: [Enter value]
            - name: SCIHUB_USERNAME
              value: [Enter value]
            - name: SCIHUB_PASSWORD
              value: [Enter value]
            - name: SOBLOO_APIKEY
              value: [Enter value]
            - name: MUNDI_SEEED_TOKEN
              value: [Enter value]
            - name: GCS_PROVIDER_BUCKETS
              value: [Enter value]
          args:
            - "--pgq-connection=$(DB_CONNECTION)"
            - "--job-queue=ingester-downloader"
            - "--event-queue=ingester-events"
            - "--storage-uri=$(STORAGE_URI)"
            - "--peps-username=$(PEPS_USERNAME)"
            - "--peps-password=$(PEPS_PASSWORD)"
            - "--onda-username=$(ONDA_USERNAME)"
            - "--onda-password=$(ONDA_PASSWORD)"
            - "--scihub-username=$(SCIHUB_USERNAME)"
            - "--scihub-password=$(SCIHUB_PASSWORD)"
            - "--creodias-username=$(CREODIAS_USERNAME)"
            - "--creodias-password=$(CREODIAS_PASSWORD)"
            - "--sobloo-apikey=$(SOBLOO_APIKEY)"
            - "--gs-provider-buckets=$(GCS_PROVIDER_BUCKETS)"
            - "--mundi-seeed-token=$(MUNDI_SEEED_TOKEN)"
          image: {{DOWNLOADER_IMAGE}}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              memory: 16Gi
            requests:
              cpu: 1900m
              memory: 7Gi
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /local-ssd
              mountPropagation: None
              name: local-ssd
      terminationGracePeriodSeconds: 5
      tolerations:
        - effect: NoSchedule
          key: preemptible
          operator: Equal
          value: "true"
      volumes:
        - name: local-ssd
          hostPath:
            path: /mnt/disks/ssd0
            type: ""
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: ingester-processor
  name: ingester-processor
  namespace: ingester
spec:
  replicas: 0
  selector:
    app: ingester-processor
  template:
    metadata:
      labels:
        app: ingester-processor
    spec:
      containers:
        - name: docker-daemon
          image: docker:20.10.17-dind
          imagePullPolicy: Always
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - mountPath: /local-ssd
              mountPropagation: None
              name: local-ssd
        - name: ingester-processor
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: DOCKER_REGISTRY_PASSWORD
              value: [Enter value]
            - name: GEOCUBE_SERVER
              value: [Enter value]
            - name: GEOCUBE_CLIENTAPIKEY
              value: [Enter value]
            - name: STORAGE_URI
              value: [Enter value]
            - name: DB_CONNECTION
              value: [Enter value]
          args:
            - "--pgq-connection=$(DB_CONNECTION)"
            - "--job-queue=ingester-processor"
            - "--event-queue=ingester-events"
            - "--storage-uri=$(STORAGE_URI)"
            - "--geocube-server=$(GEOCUBE_SERVER)"
            - "--geocube-apikey=$(GEOCUBE_CLIENTAPIKEY)"
            - "--docker-registry-username=_json_key"
            - "--docker-registry-password=$(DOCKER_REGISTRY_PASSWORD)"
            - "--docker-registry-server=..."
            - "--docker-credentials-filepath=..."
            - "--docker-envs=..."
            - "--with-docker-engine"
          image: {{PROCESSOR_IMAGE}}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              memory: 16Gi
            requests:
              cpu: 1900m
              memory: 1500Mi
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /local-ssd
              mountPropagation: None
              name: local-ssd
      terminationGracePeriodSeconds: 5
      tolerations:
        - effect: NoSchedule
          key: preemptible
          operator: Equal
          value: "true"
      volumes:
        - name: local-ssd
          hostPath:
            path: /mnt/disks/ssd0
            type: ""

---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingester-workflow-sa
  namespace: ingester

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingester-autoscaled-pods
  namespace: ingester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingester-autoscaler-role
subjects:
  - kind: ServiceAccount
    name: ingester-workflow-sa
    namespace: ingester

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingester-autoscaler-role
  namespace: ingester
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - create
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
    verbs:
      - get
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: ingester
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ingester-workflow
  sessionAffinity: None
  type: NodePort
