// Code generated by "enumer -json -sql -type Status -trimprefix Status"; DO NOT EDIT.

package common

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _StatusName = "NEWPENDINGDONEFAILEDRETRY"

var _StatusIndex = [...]uint8{0, 3, 10, 14, 20, 25}

const _StatusLowerName = "newpendingdonefailedretry"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusNEW-(0)]
	_ = x[StatusPENDING-(1)]
	_ = x[StatusDONE-(2)]
	_ = x[StatusFAILED-(3)]
	_ = x[StatusRETRY-(4)]
}

var _StatusValues = []Status{StatusNEW, StatusPENDING, StatusDONE, StatusFAILED, StatusRETRY}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:3]:        StatusNEW,
	_StatusLowerName[0:3]:   StatusNEW,
	_StatusName[3:10]:       StatusPENDING,
	_StatusLowerName[3:10]:  StatusPENDING,
	_StatusName[10:14]:      StatusDONE,
	_StatusLowerName[10:14]: StatusDONE,
	_StatusName[14:20]:      StatusFAILED,
	_StatusLowerName[14:20]: StatusFAILED,
	_StatusName[20:25]:      StatusRETRY,
	_StatusLowerName[20:25]: StatusRETRY,
}

var _StatusNames = []string{
	_StatusName[0:3],
	_StatusName[3:10],
	_StatusName[10:14],
	_StatusName[14:20],
	_StatusName[20:25],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Status
func (i Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Status
func (i *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}

	var err error
	*i, err = StatusString(s)
	return err
}

func (i Status) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Status) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Status: %[1]T(%[1]v)", value)
	}

	val, err := StatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
